### PR TITLE
Use PLOS style guidelines

### PR DESCRIPTION
**Pull request by drvinceknight**
This is a PR from `plos-vk` to a `plos` branch. Currently the `plos` branch is where our previous submission was.

I've essentially moved everything in to a `plos` dir and followed their specification:

- Remove section headings
- Move all input files to main text;
- Move graphics files
- Add extra images to appendix

(Sorry the diff isn't too helpful.)

Note the last point (putting the "extra" images in the appendix). For IEEE we were asked to put them in supplementary materials, @marcharper you weren't too excited about this so perhaps this is a nice opportunity to move them back in to the main text?

### CODE REVIEW

**Comment by marcharper** [comment]
Yeah I think we should move some of the images, particularly those that track all the strategies as population size varies, back into the main text.

**Comment by drvinceknight** [comment]
> Yeah I think we should move some of the images, particularly those that track all the strategies as population size varies, back into the main text.

Will do. :+1:

**Comment by drvinceknight** [comment]
I've moved the 3 ranks v pop size in to the main text. I think the others can stay in that appendix but let me know. The diffs are all huge and horrible, probably best/easiest to look over the pdf for anything specific we'd like to change further. 

I haven't made any actual modifications, just style changes but some of this had to be done manually so I'll be rereading over carefully before we submit (just in case I've done something stupid).

**Comment by marcharper** [comment]
Looks good to me, thanks for doing this. A few minor comments:
* Figure 1 is a bit small
* Some of the large figures would be better in landscape or full page mode, if they allow that. I presume in the appendix that is ok. Doesn't matter for the web version though.

**Comment by drvinceknight** [comment]
Thanks @marcharper I'll address those over next few days and then circulate to everyone before submitting :+1:

**Comment by drvinceknight** [comment]
> Some of the large figures would be better in landscape or full page mode, if they allow that. I presume in the appendix that is ok. Doesn't matter for the web version though.

The PLOS Style file has a BIG left margin so I'm not sure they would look any better, for most they essentially are in full page mode. Do you have a specific figure you'd like me to try in landscape?

**Comment by marcharper** [comment]
Not particularly, I'll leave it up to you

**Comment by Nikoleta-v3** [comment]
Everything looks great, thank you for your time @drvinceknight. Just a few minor stuff for me: https://github.com/Axelrod-Python/axelrod-moran/pull/71

**Comment by drvinceknight** [comment]
I'll submit over next couple of days :+1:

**Comment by marcharper** [comment]
thanks!

**Pull request merged**
