### PR TITLE
Fix action in tf2 diagram and add sentence.

### PR DESCRIPTION
**Pull request by drvinceknight**
Have added a sentence about 2 unreachable states.

@Nikoleta-v3 could you take a look at the change I've made to the tf2 diagram please, based on this line from the FSM

```
25      (3, C, 0, C), (3, D, 1, D),
```

### CODE REVIEW

**Comment by Nikoleta-v3** [comment]
Thank you for pointing that out. I will go through them once again now to make sure the rest is good to go!

**Comment by marcharper** [comment]
It was the tests that caught this one when I added the strategies to the library, so thanks to whomever added those!

**Comment by drvinceknight** [comment]
@Nikoleta-v3 and I have checked all the fsm diagrams and they are correct:

```python
import collections
import imp
players = imp.load_source('players', '../src/players.py')

def tikz_line_to_transition(line):
    """Parse a tikz line corresponding to an edge"""
    current_state = int(line[line.index("(") + 1: line.index(")")])
    next_state = int(line[line.index("(", line.index("(") +1) + 1: line.index(")", line.index(")") +1)])
    input_action, output_action = line[line.index("{$") + 2: line.index("$}")].split("/")

    return (current_state, input_action, next_state, output_action)
    

def convert_tex_fsm(fsm_file):
    fsm = []
    with open(fsm_file, "r") as f:
        for line in f:
            if "\\draw" in line and not "(s)" in line:  # Pick out lines corresponding to an edge
                fsm.append(tikz_line_to_transition(line))
    return fsm


for i, tex_file in enumerate(["fsm_one.tex", "fsm_two.tex", "fsm_three.tex"]):
    print(sorted(players.fsm_transitions[i]) == sorted(convert_tex_fsm(tex_file)))
```

output:

```python
True
True
True
```

**Comment by marcharper** [comment]
Ok so the numbering is off by one, and in fact states 5 and 6 are unreachable for TF2?

**Pull request merged**
