### PR TITLE
Nik

### PR DESCRIPTION
**Pull request by Nikoleta-v3**
Representations of strategies fortress 3 and fortress 4. 

Please let me know if they don't look like you wanted (if there are ugly) .

### CODE REVIEW

**Comment by drvinceknight** [comment]
@Nikoleta-v3 I meant to plot the extra 3 FSM strategies used in this, so not the ones from the literature but the 3 ones specifically chosen (see `src/players.py`).

**Comment by Nikoleta-v3** [comment]
I see. Sorry about that.

**Comment by marcharper** [comment]
Thanks for making these! Maybe we can put them in an appendix for comparison to the new ones (at least for the ArXiv perhaps?). Fingers crossed that we've chased down the last issue for the FSM players -- my expectations are high!

You might also consider some of the players in the library, say EvolvedFSM4. We'll need it for the ML paper  anyway.

**Comment by drvinceknight** [comment]
> Fingers crossed that we've chased down the last issue for the FSM players -- my expectations are high!

So there's actually 6 extra FSM :) Not sure if you followed on #20 but I actually had the wrong FSMs. Thankfully it's just the initial state that differs to what's currently there so shouldn't be too much of a pain to modify :) We can chat about if in our meeting tomorrow :+1:

**Comment by Nikoleta-v3** [comment]
#32 closes this. 

It has a better title and explanation of the additions.

**Pull request closed without merging**
